all:
	ca65 exercise_001.s -o exercise_001.o
	ld65 exercise_001.o -o exercise_001.nes -C memory_map.cfg

	ca65 exercise_002.s -o exercise_002.o
	ld65 exercise_002.o -o exercise_002.nes -C memory_map.cfg

	ca65 exercise_003.s -o exercise_003.o
	ld65 exercise_003.o -o exercise_003.nes -C memory_map.cfg

	ca65 exercise_004.s -o exercise_004.o
	ld65 exercise_004.o -o exercise_004.nes -C memory_map.cfg

	ca65 exercise_005.s -o exercise_005.o
	ld65 exercise_005.o -o exercise_005.nes -C memory_map.cfg

	ca65 exercise_006.s -o exercise_006.o
	ld65 exercise_006.o -o exercise_006.nes -C memory_map.cfg

	ca65 exercise_007.s -o exercise_007.o
	ld65 exercise_007.o -o exercise_007.nes -C memory_map.cfg

	ca65 exercise_008.s -o exercise_008.o
	ld65 exercise_008.o -o exercise_008.nes -C memory_map.cfg

	ca65 exercise_009.s -o exercise_009.o
	ld65 exercise_009.o -o exercise_009.nes -C memory_map.cfg

clean:
	rm *.o *.nes